### ISSUE TITLE
suggestion for removing buttom ribbon 

### ISSUE THREAD

**Issue by alighamari** [MahStudio/Denna#51]
![image](https://user-images.githubusercontent.com/24440862/44156887-46b17096-a0c6-11e8-9d00-29ee65e6f8d3.png)
you can add this two buttons to top header and remove whole bottom section for saving space

**Comment by Mohsens22** [comment]
Thanks for your recommendation. I'm going to close this issue, but feel free to re open it when you feel it makes sense.
I'm not going to apply this change because: 
1. This is designed by our senior designer
2. If I do this, It will beak app UI's coherency. App bar is for actions (navigation), while pivot is for moving from one view of the app to another. Complete different tasks.
3. User expects to see + button and settings at the button just like V1. So If I do a change, Denna's UX will suck.
